apiVersion: v1
kind: Secret
metadata:
  name: jfrog-registry-secret
  namespace: vault-deployment
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJ0cmlhbHAxNGZoZC5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogImFzaGlzaG1ha2FzYXJlMjRAZ21haWwuY29tIiwKICAgICAgInBhc3N3b3JkIjogIkFQNEE2VTdOa1B1SjR4WnZabk1mVkY5b1VoUCIsCiAgICAgICJlbWFpbCI6ICJ1bnVzZWRAbG9jYWxob3N0IiwKICAgICAgImF1dGgiOiAiWVhOb2FYTm9iV0ZyWVhOaGNtVXlORUJuYldGcGJDNWpiMjA2UVZBMFFUWlZOMDVyVUhWS05IaGFkbHB1VFdaV1JqbHZWV2hRIgogICAgfQogIH0KfQo=