apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0cmlhbHRwNzN6dy5qZnJvZy5pbyI6eyJ1c2VybmFtZSI6ImFzaGlzaG1ha2FzYXJlMjRAZ21haWwuY29tIiwicGFzc3dvcmQiOiJBc2hpc2hAMTIzIiwiZW1haWwiOiJ1bnVzZWRAbG9jYWxob3N0IiwiYXV0aCI6IllYTm9hWE5vYldGcllYTmhjbVV5TkVCbmJXRnBiQzVqYjIwNlFYTm9hWE5vUURFeU13PT0ifX19
kind: Secret
metadata:
  name: jfrog-registry-secret
  namespace: vault-deployment
type: kubernetes.io/dockerconfigjson
